%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 9.0746350696116758e+02
Camera.fy: 9.0746350696116758e+02
Camera.cx: 6.4506844923098583e+02
Camera.cy: 3.5923690786281225e+02

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 30.0

# stereo baseline times fx
Camera.bf: 15.899

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 35

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 720
LEFT.width: 1280
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data:[-4.3433473840346293e-01, 2.1813887582915195e-01, 7.0901088638281506e-04, -9.5529607302465285e-04, -6.2124525760800089e-02]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [9.6639889538436228e+02, 0.0, 6.4387969634890544e+02, 0.0, 9.6690682682231284e+02, 3.5706289429247789e+02, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.99993545, 0.011294018, -0.0012311875, -0.011298007, 0.9999308, -0.0032837393, 0.0011940156, 0.0032974374, 0.99999386]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [9.0746350696116758e+02, 0, 6.4506844923098583e+02, 0,  0, 9.0746350696116758e+02, 3.5923690786281225e+02, 0,  0, 0, 1, 0]

RIGHT.height: 720
RIGHT.width: 1280
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data:[-4.3311856109176949e-01, 2.1441868575793727e-01, 1.8109342471806980e-04, 3.9351719012948779e-05, -5.9133654012940094e-02]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [9.6646340505045623e+02, 0.0, 6.4153010260912845e+02, 0.0, 9.6683548394208094e+02, 3.6040667905395753e+02, 0.0, 0.0, 1]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.99993545, -0.011298007, 0.0011940156, 0.011294018, 0.9999308, 0.0032974374, -0.0012311875, -0.0032837393, 0.99999386]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [9.0746350696116758e+02, 0, 6.4506844923098583e+02, -36.289, 0, 9.0746350696116758e+02, 3.5923690786281225e+02, 0, 0, 0, 1, 0]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

